# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-16 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayedTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=256, null=True)),
                ('artist', models.CharField(blank=True, max_length=256, null=True)),
                ('track', models.CharField(blank=True, max_length=256, null=True)),
                ('playback_date', models.DateTimeField()),
                ('uid', models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
