# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-11 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastfm_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playedtrack',
            name='album',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
