# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastfm_data', '0003_playedtrack_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playedtrack',
            old_name='image',
            new_name='image_url',
        ),
        migrations.AddField(
            model_name='playedtrack',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='album_images'),
        ),
    ]
