# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lastfm_data', '0004_auto_20160809_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playedtrack',
            name='image_url',
        ),
    ]
