# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-17 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lastfm_data', '0006_auto_20160817_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='playedtrack',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lastfm_data.Album'),
        ),
        migrations.AddField(
            model_name='playedtrack',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lastfm_data.Artist'),
        ),
    ]
