# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastfm_data', '0008_auto_20160822_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='tracks_count',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
