# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-28 09:03
from __future__ import unicode_literals

from django.db import migrations



def create_user(apps, schema_editor):
    # We can't import the ServiceUser model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    ServiceUser = apps.get_model("lastfm_data", "ServiceUser")
    PlayedTrack = apps.get_model("lastfm_data", "PlayedTrack")
    for played_track in PlayedTrack.objects.all():
        suser, created = ServiceUser.objects.get_or_create(username=played_track.user_old)
        played_track.user = suser
        played_track.save()



class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('lastfm_data', '0011_auto_20160928_0853'),
    ]

    operations = [
        migrations.RunPython(create_user)
    ]
