# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-28 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lastfm_data', '0012_auto_20160928_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playedtrack',
            name='user_old',
        ),
    ]
