# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-02 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastfm_data', '0013_remove_playedtrack_user_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceuser',
            name='username',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together=set([('name', 'artist')]),
        ),
    ]
